const {JSDOM}=require('jsdom'), fs=require('fs'), assert=require('node:assert/strict');
const root=require('node:path').join(__dirname,'../docs');
const html=fs.readFileSync(root+'/index.html','utf8'),app=fs.readFileSync(root+'/app.js','utf8'),actual=JSON.parse(fs.readFileSync(root+'/data.json','utf8'));
async function boot(payload,fail=false){const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.fetch=async()=>({ok:!fail,status:fail?503:200,json:async()=>payload});w.URL.createObjectURL=()=> 'blob:qa';w.URL.revokeObjectURL=()=>{};w.console.error=()=>{};w.eval(app);await new Promise(r=>setTimeout(r,0));return w}
(async()=>{let w=await boot(actual),d=w.document;assert.equal(d.getElementById('index').textContent,'100.00');assert.equal(d.querySelectorAll('#chart path').length,1);assert.equal(d.querySelectorAll('#constituents tr').length,10);
d.querySelector('[data-range="7"]').click();assert.match(d.getElementById('range-summary').textContent,/2026-09-25/);d.getElementById('compare').click();assert.equal(d.querySelectorAll('#chart path').length,3);d.getElementById('average').click();assert.equal(d.querySelectorAll('#chart path').length,4);d.getElementById('relative').click();assert.ok(d.querySelectorAll('#chart path')[3].getAttribute('d').length>0);
d.getElementById('chart').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));assert.equal(d.getElementById('tooltip').hidden,false);assert.match(d.getElementById('tooltip').textContent,/ACPI 100.00/);d.querySelector('[data-layer="api"]').click();assert.equal(d.querySelectorAll('#constituents tr').length,3);assert.ok(!d.body.textContent.includes('NaN'));
const missing=structuredClone(actual);Object.assign(missing.level.at(-1),{acpi_level:null,chg_1d_pct:null,expired:2,coverage:11,quality_flag:'incomplete'});w=await boot(missing);assert.equal(w.document.getElementById('index').textContent,'—');assert.match(w.document.getElementById('daily').textContent,/Unavailable/);assert.equal(w.document.getElementById('quality').hidden,false);
w=await boot(actual,true);assert.match(w.document.getElementById('error').textContent,/503/);assert.equal(w.document.getElementById('error').hidden,false);
const method=new JSDOM(fs.readFileSync(root+'/methodology.html','utf8'),{runScripts:'dangerously'});assert.equal(method.window.document.getElementById('example-result').textContent,'85.54');method.window.document.getElementById('gpu-slider').value=0;method.window.document.getElementById('gpu-slider').dispatchEvent(new method.window.Event('input'));assert.equal(method.window.document.getElementById('example-result').textContent,'100.00');
console.log('PASS: chart, ranges, compare, MA/rebase, keyboard tooltip, basket tabs, missing data, load errors, interactive methodology.');
})().catch(e=>{console.error(e);process.exit(1)});
